package cn.zttek.thesis.modules.model;

import java.sql.Timestamp;

@SuppressWarnings("serial")
public class Apply extends ThesisModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.projid
     *
     * @mbggenerated
     */
    private Long projid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.studentid
     *
     * @mbggenerated
     */
    private Long studentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.apply_info
     *
     * @mbggenerated
     */
    private String applyInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.apply_time
     *
     * @mbggenerated
     */
    private Timestamp applyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.teacherid
     *
     * @mbggenerated
     */
    private Long teacherid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.reply_info
     *
     * @mbggenerated
     */
    private String replyInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.reply_time
     *
     * @mbggenerated
     */
    private Timestamp replyTime;

    private String topic;
    private String teacher;
    private String stuno;
    private String student;

    public String getTopic() {
        return topic;
    }

    public void setTopic(String topic) {
        this.topic = topic;
    }

    public String getTeacher() {
        return teacher;
    }

    public void setTeacher(String teacher) {
        this.teacher = teacher;
    }

    public String getStuno() {
        return stuno;
    }

    public void setStuno(String stuno) {
        this.stuno = stuno;
    }

    public String getStudent() {
        return student;
    }

    public void setStudent(String student) {
        this.student = student;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.projid
     *
     * @return the value of apply.projid
     *
     * @mbggenerated
     */
    public Long getProjid() {
        return projid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.projid
     *
     * @param projid the value for apply.projid
     *
     * @mbggenerated
     */
    public void setProjid(Long projid) {
        this.projid = projid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.studentid
     *
     * @return the value of apply.studentid
     *
     * @mbggenerated
     */
    public Long getStudentid() {
        return studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.studentid
     *
     * @param studentid the value for apply.studentid
     *
     * @mbggenerated
     */
    public void setStudentid(Long studentid) {
        this.studentid = studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.apply_info
     *
     * @return the value of apply.apply_info
     *
     * @mbggenerated
     */
    public String getApplyInfo() {
        return applyInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.apply_info
     *
     * @param applyInfo the value for apply.apply_info
     *
     * @mbggenerated
     */
    public void setApplyInfo(String applyInfo) {
        this.applyInfo = applyInfo == null ? null : applyInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.apply_time
     *
     * @return the value of apply.apply_time
     *
     * @mbggenerated
     */
    public Timestamp getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.apply_time
     *
     * @param applyTime the value for apply.apply_time
     *
     * @mbggenerated
     */
    public void setApplyTime(Timestamp applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.teacherid
     *
     * @return the value of apply.teacherid
     *
     * @mbggenerated
     */
    public Long getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.teacherid
     *
     * @param teacherid the value for apply.teacherid
     *
     * @mbggenerated
     */
    public void setTeacherid(Long teacherid) {
        this.teacherid = teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.reply_info
     *
     * @return the value of apply.reply_info
     *
     * @mbggenerated
     */
    public String getReplyInfo() {
        return replyInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.reply_info
     *
     * @param replyInfo the value for apply.reply_info
     *
     * @mbggenerated
     */
    public void setReplyInfo(String replyInfo) {
        this.replyInfo = replyInfo == null ? null : replyInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.reply_time
     *
     * @return the value of apply.reply_time
     *
     * @mbggenerated
     */
    public Timestamp getReplyTime() {
        return replyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.reply_time
     *
     * @param replyTime the value for apply.reply_time
     *
     * @mbggenerated
     */
    public void setReplyTime(Timestamp replyTime) {
        this.replyTime = replyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", projid=").append(projid);
        sb.append(", studentid=").append(studentid);
        sb.append(", applyInfo=").append(applyInfo);
        sb.append(", applyTime=").append(applyTime);
        sb.append(", teacherid=").append(teacherid);
        sb.append(", replyInfo=").append(replyInfo);
        sb.append(", replyTime=").append(replyTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Apply other = (Apply) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getProjid() == null ? other.getProjid() == null : this.getProjid().equals(other.getProjid()))
                && (this.getThesisid() == null ? other.getThesisid() == null : this.getThesisid().equals(other.getThesisid()))
                && (this.getStudentid() == null ? other.getStudentid() == null : this.getStudentid().equals(other.getStudentid()))
                && (this.getApplyInfo() == null ? other.getApplyInfo() == null : this.getApplyInfo().equals(other.getApplyInfo()))
                && (this.getApplyTime() == null ? other.getApplyTime() == null : this.getApplyTime().equals(other.getApplyTime()))
                && (this.getTeacherid() == null ? other.getTeacherid() == null : this.getTeacherid().equals(other.getTeacherid()))
                && (this.getReplyInfo() == null ? other.getReplyInfo() == null : this.getReplyInfo().equals(other.getReplyInfo()))
                && (this.getReplyTime() == null ? other.getReplyTime() == null : this.getReplyTime().equals(other.getReplyTime()))
                && (this.getValid() == null ? other.getValid() == null : this.getValid().equals(other.getValid()))
                && (this.getCdate() == null ? other.getCdate() == null : this.getCdate().equals(other.getCdate()))
                && (this.getMdate() == null ? other.getMdate() == null : this.getMdate().equals(other.getMdate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getProjid() == null) ? 0 : getProjid().hashCode());
        result = prime * result + ((getThesisid() == null) ? 0 : getThesisid().hashCode());
        result = prime * result + ((getStudentid() == null) ? 0 : getStudentid().hashCode());
        result = prime * result + ((getApplyInfo() == null) ? 0 : getApplyInfo().hashCode());
        result = prime * result + ((getApplyTime() == null) ? 0 : getApplyTime().hashCode());
        result = prime * result + ((getTeacherid() == null) ? 0 : getTeacherid().hashCode());
        result = prime * result + ((getReplyInfo() == null) ? 0 : getReplyInfo().hashCode());
        result = prime * result + ((getReplyTime() == null) ? 0 : getReplyTime().hashCode());
        result = prime * result + ((getValid() == null) ? 0 : getValid().hashCode());
        result = prime * result + ((getCdate() == null) ? 0 : getCdate().hashCode());
        result = prime * result + ((getMdate() == null) ? 0 : getMdate().hashCode());
        return result;
    }
}