package cn.zttek.thesis.modules.model;

import java.sql.Timestamp;

@SuppressWarnings("serial")
public class Group extends ProjectModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tgroup.groupno
     *
     * @mbggenerated
     */
    private String groupno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tgroup.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tgroup.leader
     *
     * @mbggenerated
     */
    private Long leader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tgroup.secret
     *
     * @mbggenerated
     */
    private Long secret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tgroup.teachers
     *
     * @mbggenerated
     */
    private String teachers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tgroup.students
     *
     * @mbggenerated
     */
    private String students;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tgroup.dtime
     *
     * @mbggenerated
     */
    private Timestamp dtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tgroup.droom
     *
     * @mbggenerated
     */
    private String droom;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tgroup.groupno
     *
     * @return the value of tgroup.groupno
     *
     * @mbggenerated
     */
    public String getGroupno() {
        return groupno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tgroup.groupno
     *
     * @param groupno the value for tgroup.groupno
     *
     * @mbggenerated
     */
    public void setGroupno(String groupno) {
        this.groupno = groupno == null ? null : groupno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tgroup.type
     *
     * @return the value of tgroup.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tgroup.type
     *
     * @param type the value for tgroup.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tgroup.leader
     *
     * @return the value of tgroup.leader
     *
     * @mbggenerated
     */
    public Long getLeader() {
        return leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tgroup.leader
     *
     * @param leader the value for tgroup.leader
     *
     * @mbggenerated
     */
    public void setLeader(Long leader) {
        this.leader = leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tgroup.secret
     *
     * @return the value of tgroup.secret
     *
     * @mbggenerated
     */
    public Long getSecret() {
        return secret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tgroup.secret
     *
     * @param secret the value for tgroup.secret
     *
     * @mbggenerated
     */
    public void setSecret(Long secret) {
        this.secret = secret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tgroup.teachers
     *
     * @return the value of tgroup.teachers
     *
     * @mbggenerated
     */
    public String getTeachers() {
        return teachers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tgroup.teachers
     *
     * @param teachers the value for tgroup.teachers
     *
     * @mbggenerated
     */
    public void setTeachers(String teachers) {
        this.teachers = teachers == null ? null : teachers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tgroup.students
     *
     * @return the value of tgroup.students
     *
     * @mbggenerated
     */
    public String getStudents() {
        return students;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tgroup.students
     *
     * @param students the value for tgroup.students
     *
     * @mbggenerated
     */
    public void setStudents(String students) {
        this.students = students == null ? null : students.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tgroup.dtime
     *
     * @return the value of tgroup.dtime
     *
     * @mbggenerated
     */
    public Timestamp getDtime() {
        return dtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tgroup.dtime
     *
     * @param dtime the value for tgroup.dtime
     *
     * @mbggenerated
     */
    public void setDtime(Timestamp dtime) {
        this.dtime = dtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tgroup.droom
     *
     * @return the value of tgroup.droom
     *
     * @mbggenerated
     */
    public String getDroom() {
        return droom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tgroup.droom
     *
     * @param droom the value for tgroup.droom
     *
     * @mbggenerated
     */
    public void setDroom(String droom) {
        this.droom = droom == null ? null : droom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tgroup
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", groupno=").append(groupno);
        sb.append(", type=").append(type);
        sb.append(", leader=").append(leader);
        sb.append(", secret=").append(secret);
        sb.append(", teachers=").append(teachers);
        sb.append(", students=").append(students);
        sb.append(", dtime=").append(dtime);
        sb.append(", droom=").append(droom);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tgroup
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Group other = (Group) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getProjid() == null ? other.getProjid() == null : this.getProjid().equals(other.getProjid()))
            && (this.getGroupno() == null ? other.getGroupno() == null : this.getGroupno().equals(other.getGroupno()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getLeader() == null ? other.getLeader() == null : this.getLeader().equals(other.getLeader()))
            && (this.getSecret() == null ? other.getSecret() == null : this.getSecret().equals(other.getSecret()))
            && (this.getTeachers() == null ? other.getTeachers() == null : this.getTeachers().equals(other.getTeachers()))
            && (this.getStudents() == null ? other.getStudents() == null : this.getStudents().equals(other.getStudents()))
            && (this.getDtime() == null ? other.getDtime() == null : this.getDtime().equals(other.getDtime()))
            && (this.getDroom() == null ? other.getDroom() == null : this.getDroom().equals(other.getDroom()))
            && (this.getValid() == null ? other.getValid() == null : this.getValid().equals(other.getValid()))
            && (this.getCdate() == null ? other.getCdate() == null : this.getCdate().equals(other.getCdate()))
            && (this.getMdate() == null ? other.getMdate() == null : this.getMdate().equals(other.getMdate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tgroup
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getProjid() == null) ? 0 : getProjid().hashCode());
        result = prime * result + ((getGroupno() == null) ? 0 : getGroupno().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getLeader() == null) ? 0 : getLeader().hashCode());
        result = prime * result + ((getSecret() == null) ? 0 : getSecret().hashCode());
        result = prime * result + ((getTeachers() == null) ? 0 : getTeachers().hashCode());
        result = prime * result + ((getStudents() == null) ? 0 : getStudents().hashCode());
        result = prime * result + ((getDtime() == null) ? 0 : getDtime().hashCode());
        result = prime * result + ((getDroom() == null) ? 0 : getDroom().hashCode());
        result = prime * result + ((getValid() == null) ? 0 : getValid().hashCode());
        result = prime * result + ((getCdate() == null) ? 0 : getCdate().hashCode());
        result = prime * result + ((getMdate() == null) ? 0 : getMdate().hashCode());
        return result;
    }
}