package cn.zttek.thesis.modules.model;

@SuppressWarnings("serial")
public class Midcheck extends ThesisModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column midcheck.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column midcheck.schedule
     *
     * @mbggenerated
     */
    private String schedule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column midcheck.reference
     *
     * @mbggenerated
     */
    private String reference;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column midcheck.advice
     *
     * @mbggenerated
     */
    private String advice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column midcheck.tconfirm
     *
     * @mbggenerated
     */
    private Boolean tconfirm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column midcheck.sconfirm
     *
     * @mbggenerated
     */
    private Boolean sconfirm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column midcheck.content
     *
     * @return the value of midcheck.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column midcheck.content
     *
     * @param content the value for midcheck.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column midcheck.schedule
     *
     * @return the value of midcheck.schedule
     *
     * @mbggenerated
     */
    public String getSchedule() {
        return schedule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column midcheck.schedule
     *
     * @param schedule the value for midcheck.schedule
     *
     * @mbggenerated
     */
    public void setSchedule(String schedule) {
        this.schedule = schedule == null ? null : schedule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column midcheck.reference
     *
     * @return the value of midcheck.reference
     *
     * @mbggenerated
     */
    public String getReference() {
        return reference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column midcheck.reference
     *
     * @param reference the value for midcheck.reference
     *
     * @mbggenerated
     */
    public void setReference(String reference) {
        this.reference = reference == null ? null : reference.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column midcheck.advice
     *
     * @return the value of midcheck.advice
     *
     * @mbggenerated
     */
    public String getAdvice() {
        return advice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column midcheck.advice
     *
     * @param advice the value for midcheck.advice
     *
     * @mbggenerated
     */
    public void setAdvice(String advice) {
        this.advice = advice == null ? null : advice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column midcheck.tconfirm
     *
     * @return the value of midcheck.tconfirm
     *
     * @mbggenerated
     */
    public Boolean getTconfirm() {
        return tconfirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column midcheck.tconfirm
     *
     * @param tconfirm the value for midcheck.tconfirm
     *
     * @mbggenerated
     */
    public void setTconfirm(Boolean tconfirm) {
        this.tconfirm = tconfirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column midcheck.sconfirm
     *
     * @return the value of midcheck.sconfirm
     *
     * @mbggenerated
     */
    public Boolean getSconfirm() {
        return sconfirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column midcheck.sconfirm
     *
     * @param sconfirm the value for midcheck.sconfirm
     *
     * @mbggenerated
     */
    public void setSconfirm(Boolean sconfirm) {
        this.sconfirm = sconfirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table midcheck
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", content=").append(content);
        sb.append(", schedule=").append(schedule);
        sb.append(", reference=").append(reference);
        sb.append(", advice=").append(advice);
        sb.append(", tconfirm=").append(tconfirm);
        sb.append(", sconfirm=").append(sconfirm);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table midcheck
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Midcheck other = (Midcheck) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getThesisid() == null ? other.getThesisid() == null : this.getThesisid().equals(other.getThesisid()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getSchedule() == null ? other.getSchedule() == null : this.getSchedule().equals(other.getSchedule()))
            && (this.getReference() == null ? other.getReference() == null : this.getReference().equals(other.getReference()))
            && (this.getAdvice() == null ? other.getAdvice() == null : this.getAdvice().equals(other.getAdvice()))
            && (this.getTconfirm() == null ? other.getTconfirm() == null : this.getTconfirm().equals(other.getTconfirm()))
            && (this.getSconfirm() == null ? other.getSconfirm() == null : this.getSconfirm().equals(other.getSconfirm()))
            && (this.getValid() == null ? other.getValid() == null : this.getValid().equals(other.getValid()))
            && (this.getCdate() == null ? other.getCdate() == null : this.getCdate().equals(other.getCdate()))
            && (this.getMdate() == null ? other.getMdate() == null : this.getMdate().equals(other.getMdate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table midcheck
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getThesisid() == null) ? 0 : getThesisid().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getSchedule() == null) ? 0 : getSchedule().hashCode());
        result = prime * result + ((getReference() == null) ? 0 : getReference().hashCode());
        result = prime * result + ((getAdvice() == null) ? 0 : getAdvice().hashCode());
        result = prime * result + ((getTconfirm() == null) ? 0 : getTconfirm().hashCode());
        result = prime * result + ((getSconfirm() == null) ? 0 : getSconfirm().hashCode());
        result = prime * result + ((getValid() == null) ? 0 : getValid().hashCode());
        result = prime * result + ((getCdate() == null) ? 0 : getCdate().hashCode());
        result = prime * result + ((getMdate() == null) ? 0 : getMdate().hashCode());
        return result;
    }
}