package cn.zttek.thesis.modules.model;

import cn.zttek.thesis.common.base.BaseModel;
import java.sql.Timestamp;

@SuppressWarnings("serial")
public class Org extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org.projlimit
     *
     * @mbggenerated
     */
    private Integer projlimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org.studlimit
     *
     * @mbggenerated
     */
    private Integer studlimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org.uploadlimit
     *
     * @mbggenerated
     */
    private Integer uploadlimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org.docroot
     *
     * @mbggenerated
     */
    private String docroot;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org.name
     *
     * @return the value of org.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org.name
     *
     * @param name the value for org.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org.projlimit
     *
     * @return the value of org.projlimit
     *
     * @mbggenerated
     */
    public Integer getProjlimit() {
        return projlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org.projlimit
     *
     * @param projlimit the value for org.projlimit
     *
     * @mbggenerated
     */
    public void setProjlimit(Integer projlimit) {
        this.projlimit = projlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org.studlimit
     *
     * @return the value of org.studlimit
     *
     * @mbggenerated
     */
    public Integer getStudlimit() {
        return studlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org.studlimit
     *
     * @param studlimit the value for org.studlimit
     *
     * @mbggenerated
     */
    public void setStudlimit(Integer studlimit) {
        this.studlimit = studlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org.uploadlimit
     *
     * @return the value of org.uploadlimit
     *
     * @mbggenerated
     */
    public Integer getUploadlimit() {
        return uploadlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org.uploadlimit
     *
     * @param uploadlimit the value for org.uploadlimit
     *
     * @mbggenerated
     */
    public void setUploadlimit(Integer uploadlimit) {
        this.uploadlimit = uploadlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org.docroot
     *
     * @return the value of org.docroot
     *
     * @mbggenerated
     */
    public String getDocroot() {
        return docroot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org.docroot
     *
     * @param docroot the value for org.docroot
     *
     * @mbggenerated
     */
    public void setDocroot(String docroot) {
        this.docroot = docroot == null ? null : docroot.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(getId());
        sb.append(", name=").append(name);
        sb.append(", projlimit=").append(projlimit);
        sb.append(", studlimit=").append(studlimit);
        sb.append(", uploadlimit=").append(uploadlimit);
        sb.append(", docroot=").append(docroot);
        sb.append(", valid=").append(getValid());
        sb.append(", cdate=").append(getCdate());
        sb.append(", mdate=").append(getMdate());
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Org other = (Org) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getProjlimit() == null ? other.getProjlimit() == null : this.getProjlimit().equals(other.getProjlimit()))
            && (this.getStudlimit() == null ? other.getStudlimit() == null : this.getStudlimit().equals(other.getStudlimit()))
            && (this.getUploadlimit() == null ? other.getUploadlimit() == null : this.getUploadlimit().equals(other.getUploadlimit()))
            && (this.getDocroot() == null ? other.getDocroot() == null : this.getDocroot().equals(other.getDocroot()))
            && (this.getValid() == null ? other.getValid() == null : this.getValid().equals(other.getValid()))
            && (this.getCdate() == null ? other.getCdate() == null : this.getCdate().equals(other.getCdate()))
            && (this.getMdate() == null ? other.getMdate() == null : this.getMdate().equals(other.getMdate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getProjlimit() == null) ? 0 : getProjlimit().hashCode());
        result = prime * result + ((getStudlimit() == null) ? 0 : getStudlimit().hashCode());
        result = prime * result + ((getUploadlimit() == null) ? 0 : getUploadlimit().hashCode());
        result = prime * result + ((getDocroot() == null) ? 0 : getDocroot().hashCode());
        result = prime * result + ((getValid() == null) ? 0 : getValid().hashCode());
        result = prime * result + ((getCdate() == null) ? 0 : getCdate().hashCode());
        result = prime * result + ((getMdate() == null) ? 0 : getMdate().hashCode());
        return result;
    }
}