package cn.zttek.thesis.modules.model;

@SuppressWarnings("serial")
public class Pproperty extends OrgModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pproperty.property
     *
     * @mbggenerated
     */
    private String property;

    public Pproperty() {
    }

    public Pproperty(String property) {
        this.property = property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pproperty.property
     *
     * @return the value of pproperty.property
     *
     * @mbggenerated
     */
    public String getProperty() {
        return property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pproperty.property
     *
     * @param property the value for pproperty.property
     *
     * @mbggenerated
     */
    public void setProperty(String property) {
        this.property = property == null ? null : property.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pproperty
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", property=").append(property);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pproperty
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Pproperty other = (Pproperty) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOrgid() == null ? other.getOrgid() == null : this.getOrgid().equals(other.getOrgid()))
            && (this.getProperty() == null ? other.getProperty() == null : this.getProperty().equals(other.getProperty()))
            && (this.getValid() == null ? other.getValid() == null : this.getValid().equals(other.getValid()))
            && (this.getCdate() == null ? other.getCdate() == null : this.getCdate().equals(other.getCdate()))
            && (this.getMdate() == null ? other.getMdate() == null : this.getMdate().equals(other.getMdate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pproperty
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOrgid() == null) ? 0 : getOrgid().hashCode());
        result = prime * result + ((getProperty() == null) ? 0 : getProperty().hashCode());
        result = prime * result + ((getValid() == null) ? 0 : getValid().hashCode());
        result = prime * result + ((getCdate() == null) ? 0 : getCdate().hashCode());
        result = prime * result + ((getMdate() == null) ? 0 : getMdate().hashCode());
        return result;
    }
}