package cn.zttek.thesis.modules.model;

import java.util.Date;

@SuppressWarnings("serial")
public class Project extends OrgModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.year
     *
     * @mbggenerated
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.startdate
     *
     * @mbggenerated
     */
    private Date startdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.enddate
     *
     * @mbggenerated
     */
    private Date enddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.midcheckdate
     *
     * @mbggenerated
     */
    private Date midcheckdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.submitdate
     *
     * @mbggenerated
     */
    private Date submitdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.defensedate
     *
     * @mbggenerated
     */
    private Date defensedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.setallowed
     *
     * @mbggenerated
     */
    private Boolean setallowed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.getallowed
     *
     * @mbggenerated
     */
    private Boolean getallowed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.postallowed
     *
     * @mbggenerated
     */
    private Boolean postallowed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.mark1allowed
     *
     * @mbggenerated
     */
    private Boolean mark1allowed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.mark2allowed
     *
     * @mbggenerated
     */
    private Boolean mark2allowed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.mark3allowed
     *
     * @mbggenerated
     */
    private Boolean mark3allowed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.gmpercent
     *
     * @mbggenerated
     */
    private Integer gmpercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.rmpercent
     *
     * @mbggenerated
     */
    private Integer rmpercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.ampercent
     *
     * @mbggenerated
     */
    private Integer ampercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.setmax
     *
     * @mbggenerated
     */
    private Integer setmax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.setmin
     *
     * @mbggenerated
     */
    private Integer setmin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.getmax
     *
     * @mbggenerated
     */
    private Integer getmax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.doctype
     *
     * @mbggenerated
     */
    private String doctype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.close
     *
     * @mbggenerated
     */
    private Boolean close;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.title
     *
     * @return the value of project.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.title
     *
     * @param title the value for project.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.year
     *
     * @return the value of project.year
     *
     * @mbggenerated
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.year
     *
     * @param year the value for project.year
     *
     * @mbggenerated
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.startdate
     *
     * @return the value of project.startdate
     *
     * @mbggenerated
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.startdate
     *
     * @param startdate the value for project.startdate
     *
     * @mbggenerated
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.enddate
     *
     * @return the value of project.enddate
     *
     * @mbggenerated
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.enddate
     *
     * @param enddate the value for project.enddate
     *
     * @mbggenerated
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.midcheckdate
     *
     * @return the value of project.midcheckdate
     *
     * @mbggenerated
     */
    public Date getMidcheckdate() {
        return midcheckdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.midcheckdate
     *
     * @param midcheckdate the value for project.midcheckdate
     *
     * @mbggenerated
     */
    public void setMidcheckdate(Date midcheckdate) {
        this.midcheckdate = midcheckdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.submitdate
     *
     * @return the value of project.submitdate
     *
     * @mbggenerated
     */
    public Date getSubmitdate() {
        return submitdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.submitdate
     *
     * @param submitdate the value for project.submitdate
     *
     * @mbggenerated
     */
    public void setSubmitdate(Date submitdate) {
        this.submitdate = submitdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.defensedate
     *
     * @return the value of project.defensedate
     *
     * @mbggenerated
     */
    public Date getDefensedate() {
        return defensedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.defensedate
     *
     * @param defensedate the value for project.defensedate
     *
     * @mbggenerated
     */
    public void setDefensedate(Date defensedate) {
        this.defensedate = defensedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.setallowed
     *
     * @return the value of project.setallowed
     *
     * @mbggenerated
     */
    public Boolean getSetallowed() {
        return setallowed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.setallowed
     *
     * @param setallowed the value for project.setallowed
     *
     * @mbggenerated
     */
    public void setSetallowed(Boolean setallowed) {
        this.setallowed = setallowed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.getallowed
     *
     * @return the value of project.getallowed
     *
     * @mbggenerated
     */
    public Boolean getGetallowed() {
        return getallowed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.getallowed
     *
     * @param getallowed the value for project.getallowed
     *
     * @mbggenerated
     */
    public void setGetallowed(Boolean getallowed) {
        this.getallowed = getallowed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.postallowed
     *
     * @return the value of project.postallowed
     *
     * @mbggenerated
     */
    public Boolean getPostallowed() {
        return postallowed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.postallowed
     *
     * @param postallowed the value for project.postallowed
     *
     * @mbggenerated
     */
    public void setPostallowed(Boolean postallowed) {
        this.postallowed = postallowed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.mark1allowed
     *
     * @return the value of project.mark1allowed
     *
     * @mbggenerated
     */
    public Boolean getMark1allowed() {
        return mark1allowed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.mark1allowed
     *
     * @param mark1allowed the value for project.mark1allowed
     *
     * @mbggenerated
     */
    public void setMark1allowed(Boolean mark1allowed) {
        this.mark1allowed = mark1allowed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.mark2allowed
     *
     * @return the value of project.mark2allowed
     *
     * @mbggenerated
     */
    public Boolean getMark2allowed() {
        return mark2allowed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.mark2allowed
     *
     * @param mark2allowed the value for project.mark2allowed
     *
     * @mbggenerated
     */
    public void setMark2allowed(Boolean mark2allowed) {
        this.mark2allowed = mark2allowed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.mark3allowed
     *
     * @return the value of project.mark3allowed
     *
     * @mbggenerated
     */
    public Boolean getMark3allowed() {
        return mark3allowed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.mark3allowed
     *
     * @param mark3allowed the value for project.mark3allowed
     *
     * @mbggenerated
     */
    public void setMark3allowed(Boolean mark3allowed) {
        this.mark3allowed = mark3allowed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.gmpercent
     *
     * @return the value of project.gmpercent
     *
     * @mbggenerated
     */
    public Integer getGmpercent() {
        return gmpercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.gmpercent
     *
     * @param gmpercent the value for project.gmpercent
     *
     * @mbggenerated
     */
    public void setGmpercent(Integer gmpercent) {
        this.gmpercent = gmpercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.rmpercent
     *
     * @return the value of project.rmpercent
     *
     * @mbggenerated
     */
    public Integer getRmpercent() {
        return rmpercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.rmpercent
     *
     * @param rmpercent the value for project.rmpercent
     *
     * @mbggenerated
     */
    public void setRmpercent(Integer rmpercent) {
        this.rmpercent = rmpercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.ampercent
     *
     * @return the value of project.ampercent
     *
     * @mbggenerated
     */
    public Integer getAmpercent() {
        return ampercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.ampercent
     *
     * @param ampercent the value for project.ampercent
     *
     * @mbggenerated
     */
    public void setAmpercent(Integer ampercent) {
        this.ampercent = ampercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.setmax
     *
     * @return the value of project.setmax
     *
     * @mbggenerated
     */
    public Integer getSetmax() {
        return setmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.setmax
     *
     * @param setmax the value for project.setmax
     *
     * @mbggenerated
     */
    public void setSetmax(Integer setmax) {
        this.setmax = setmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.setmin
     *
     * @return the value of project.setmin
     *
     * @mbggenerated
     */
    public Integer getSetmin() {
        return setmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.setmin
     *
     * @param setmin the value for project.setmin
     *
     * @mbggenerated
     */
    public void setSetmin(Integer setmin) {
        this.setmin = setmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.getmax
     *
     * @return the value of project.getmax
     *
     * @mbggenerated
     */
    public Integer getGetmax() {
        return getmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.getmax
     *
     * @param getmax the value for project.getmax
     *
     * @mbggenerated
     */
    public void setGetmax(Integer getmax) {
        this.getmax = getmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.doctype
     *
     * @return the value of project.doctype
     *
     * @mbggenerated
     */
    public String getDoctype() {
        return doctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.doctype
     *
     * @param doctype the value for project.doctype
     *
     * @mbggenerated
     */
    public void setDoctype(String doctype) {
        this.doctype = doctype == null ? null : doctype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.close
     *
     * @return the value of project.close
     *
     * @mbggenerated
     */
    public Boolean getClose() {
        return close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.close
     *
     * @param close the value for project.close
     *
     * @mbggenerated
     */
    public void setClose(Boolean close) {
        this.close = close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", title=").append(title);
        sb.append(", year=").append(year);
        sb.append(", startdate=").append(startdate);
        sb.append(", enddate=").append(enddate);
        sb.append(", midcheckdate=").append(midcheckdate);
        sb.append(", submitdate=").append(submitdate);
        sb.append(", defensedate=").append(defensedate);
        sb.append(", setallowed=").append(setallowed);
        sb.append(", getallowed=").append(getallowed);
        sb.append(", postallowed=").append(postallowed);
        sb.append(", mark1allowed=").append(mark1allowed);
        sb.append(", mark2allowed=").append(mark2allowed);
        sb.append(", mark3allowed=").append(mark3allowed);
        sb.append(", gmpercent=").append(gmpercent);
        sb.append(", rmpercent=").append(rmpercent);
        sb.append(", ampercent=").append(ampercent);
        sb.append(", setmax=").append(setmax);
        sb.append(", setmin=").append(setmin);
        sb.append(", getmax=").append(getmax);
        sb.append(", doctype=").append(doctype);
        sb.append(", close=").append(close);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Project other = (Project) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getOrgid() == null ? other.getOrgid() == null : this.getOrgid().equals(other.getOrgid()))
                && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
                && (this.getYear() == null ? other.getYear() == null : this.getYear().equals(other.getYear()))
                && (this.getStartdate() == null ? other.getStartdate() == null : this.getStartdate().equals(other.getStartdate()))
                && (this.getEnddate() == null ? other.getEnddate() == null : this.getEnddate().equals(other.getEnddate()))
                && (this.getMidcheckdate() == null ? other.getMidcheckdate() == null : this.getMidcheckdate().equals(other.getMidcheckdate()))
                && (this.getSubmitdate() == null ? other.getSubmitdate() == null : this.getSubmitdate().equals(other.getSubmitdate()))
                && (this.getDefensedate() == null ? other.getDefensedate() == null : this.getDefensedate().equals(other.getDefensedate()))
                && (this.getSetallowed() == null ? other.getSetallowed() == null : this.getSetallowed().equals(other.getSetallowed()))
                && (this.getGetallowed() == null ? other.getGetallowed() == null : this.getGetallowed().equals(other.getGetallowed()))
                && (this.getPostallowed() == null ? other.getPostallowed() == null : this.getPostallowed().equals(other.getPostallowed()))
                && (this.getMark1allowed() == null ? other.getMark1allowed() == null : this.getMark1allowed().equals(other.getMark1allowed()))
                && (this.getMark2allowed() == null ? other.getMark2allowed() == null : this.getMark2allowed().equals(other.getMark2allowed()))
                && (this.getMark3allowed() == null ? other.getMark3allowed() == null : this.getMark3allowed().equals(other.getMark3allowed()))
                && (this.getGmpercent() == null ? other.getGmpercent() == null : this.getGmpercent().equals(other.getGmpercent()))
                && (this.getRmpercent() == null ? other.getRmpercent() == null : this.getRmpercent().equals(other.getRmpercent()))
                && (this.getAmpercent() == null ? other.getAmpercent() == null : this.getAmpercent().equals(other.getAmpercent()))
                && (this.getSetmax() == null ? other.getSetmax() == null : this.getSetmax().equals(other.getSetmax()))
                && (this.getSetmin() == null ? other.getSetmin() == null : this.getSetmin().equals(other.getSetmin()))
                && (this.getGetmax() == null ? other.getGetmax() == null : this.getGetmax().equals(other.getGetmax()))
                && (this.getDoctype() == null ? other.getDoctype() == null : this.getDoctype().equals(other.getDoctype()))
                && (this.getClose() == null ? other.getClose() == null : this.getClose().equals(other.getClose()))
                && (this.getValid() == null ? other.getValid() == null : this.getValid().equals(other.getValid()))
                && (this.getCdate() == null ? other.getCdate() == null : this.getCdate().equals(other.getCdate()))
                && (this.getMdate() == null ? other.getMdate() == null : this.getMdate().equals(other.getMdate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOrgid() == null) ? 0 : getOrgid().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getYear() == null) ? 0 : getYear().hashCode());
        result = prime * result + ((getStartdate() == null) ? 0 : getStartdate().hashCode());
        result = prime * result + ((getEnddate() == null) ? 0 : getEnddate().hashCode());
        result = prime * result + ((getMidcheckdate() == null) ? 0 : getMidcheckdate().hashCode());
        result = prime * result + ((getSubmitdate() == null) ? 0 : getSubmitdate().hashCode());
        result = prime * result + ((getDefensedate() == null) ? 0 : getDefensedate().hashCode());
        result = prime * result + ((getSetallowed() == null) ? 0 : getSetallowed().hashCode());
        result = prime * result + ((getGetallowed() == null) ? 0 : getGetallowed().hashCode());
        result = prime * result + ((getPostallowed() == null) ? 0 : getPostallowed().hashCode());
        result = prime * result + ((getMark1allowed() == null) ? 0 : getMark1allowed().hashCode());
        result = prime * result + ((getMark2allowed() == null) ? 0 : getMark2allowed().hashCode());
        result = prime * result + ((getMark3allowed() == null) ? 0 : getMark3allowed().hashCode());
        result = prime * result + ((getGmpercent() == null) ? 0 : getGmpercent().hashCode());
        result = prime * result + ((getRmpercent() == null) ? 0 : getRmpercent().hashCode());
        result = prime * result + ((getAmpercent() == null) ? 0 : getAmpercent().hashCode());
        result = prime * result + ((getSetmax() == null) ? 0 : getSetmax().hashCode());
        result = prime * result + ((getSetmin() == null) ? 0 : getSetmin().hashCode());
        result = prime * result + ((getGetmax() == null) ? 0 : getGetmax().hashCode());
        result = prime * result + ((getDoctype() == null) ? 0 : getDoctype().hashCode());
        result = prime * result + ((getClose() == null) ? 0 : getClose().hashCode());
        result = prime * result + ((getValid() == null) ? 0 : getValid().hashCode());
        result = prime * result + ((getCdate() == null) ? 0 : getCdate().hashCode());
        result = prime * result + ((getMdate() == null) ? 0 : getMdate().hashCode());
        return result;
    }
}