package cn.zttek.thesis.modules.model;

import java.util.Date;

@SuppressWarnings("serial")
public class Score extends ThesisModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.mark1
     *
     * @mbggenerated
     */
    private Double mark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.comment1
     *
     * @mbggenerated
     */
    private String comment1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.mark1date
     *
     * @mbggenerated
     */
    private Date mark1date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.mark2
     *
     * @mbggenerated
     */
    private Double mark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.comment2
     *
     * @mbggenerated
     */
    private String comment2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.mark2date
     *
     * @mbggenerated
     */
    private Date mark2date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.mark3
     *
     * @mbggenerated
     */
    private Double mark3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.comment3
     *
     * @mbggenerated
     */
    private String comment3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.mark3date
     *
     * @mbggenerated
     */
    private Date mark3date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.mark1
     *
     * @return the value of score.mark1
     *
     * @mbggenerated
     */
    public Double getMark1() {
        return mark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.mark1
     *
     * @param mark1 the value for score.mark1
     *
     * @mbggenerated
     */
    public void setMark1(Double mark1) {
        this.mark1 = mark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.comment1
     *
     * @return the value of score.comment1
     *
     * @mbggenerated
     */
    public String getComment1() {
        return comment1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.comment1
     *
     * @param comment1 the value for score.comment1
     *
     * @mbggenerated
     */
    public void setComment1(String comment1) {
        this.comment1 = comment1 == null ? null : comment1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.mark1date
     *
     * @return the value of score.mark1date
     *
     * @mbggenerated
     */
    public Date getMark1date() {
        return mark1date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.mark1date
     *
     * @param mark1date the value for score.mark1date
     *
     * @mbggenerated
     */
    public void setMark1date(Date mark1date) {
        this.mark1date = mark1date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.mark2
     *
     * @return the value of score.mark2
     *
     * @mbggenerated
     */
    public Double getMark2() {
        return mark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.mark2
     *
     * @param mark2 the value for score.mark2
     *
     * @mbggenerated
     */
    public void setMark2(Double mark2) {
        this.mark2 = mark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.comment2
     *
     * @return the value of score.comment2
     *
     * @mbggenerated
     */
    public String getComment2() {
        return comment2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.comment2
     *
     * @param comment2 the value for score.comment2
     *
     * @mbggenerated
     */
    public void setComment2(String comment2) {
        this.comment2 = comment2 == null ? null : comment2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.mark2date
     *
     * @return the value of score.mark2date
     *
     * @mbggenerated
     */
    public Date getMark2date() {
        return mark2date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.mark2date
     *
     * @param mark2date the value for score.mark2date
     *
     * @mbggenerated
     */
    public void setMark2date(Date mark2date) {
        this.mark2date = mark2date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.mark3
     *
     * @return the value of score.mark3
     *
     * @mbggenerated
     */
    public Double getMark3() {
        return mark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.mark3
     *
     * @param mark3 the value for score.mark3
     *
     * @mbggenerated
     */
    public void setMark3(Double mark3) {
        this.mark3 = mark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.comment3
     *
     * @return the value of score.comment3
     *
     * @mbggenerated
     */
    public String getComment3() {
        return comment3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.comment3
     *
     * @param comment3 the value for score.comment3
     *
     * @mbggenerated
     */
    public void setComment3(String comment3) {
        this.comment3 = comment3 == null ? null : comment3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.mark3date
     *
     * @return the value of score.mark3date
     *
     * @mbggenerated
     */
    public Date getMark3date() {
        return mark3date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.mark3date
     *
     * @param mark3date the value for score.mark3date
     *
     * @mbggenerated
     */
    public void setMark3date(Date mark3date) {
        this.mark3date = mark3date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", mark1=").append(mark1);
        sb.append(", comment1=").append(comment1);
        sb.append(", mark1date=").append(mark1date);
        sb.append(", mark2=").append(mark2);
        sb.append(", comment2=").append(comment2);
        sb.append(", mark2date=").append(mark2date);
        sb.append(", mark3=").append(mark3);
        sb.append(", comment3=").append(comment3);
        sb.append(", mark3date=").append(mark3date);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Score other = (Score) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getThesisid() == null ? other.getThesisid() == null : this.getThesisid().equals(other.getThesisid()))
            && (this.getMark1() == null ? other.getMark1() == null : this.getMark1().equals(other.getMark1()))
            && (this.getComment1() == null ? other.getComment1() == null : this.getComment1().equals(other.getComment1()))
            && (this.getMark1date() == null ? other.getMark1date() == null : this.getMark1date().equals(other.getMark1date()))
            && (this.getMark2() == null ? other.getMark2() == null : this.getMark2().equals(other.getMark2()))
            && (this.getComment2() == null ? other.getComment2() == null : this.getComment2().equals(other.getComment2()))
            && (this.getMark2date() == null ? other.getMark2date() == null : this.getMark2date().equals(other.getMark2date()))
            && (this.getMark3() == null ? other.getMark3() == null : this.getMark3().equals(other.getMark3()))
            && (this.getComment3() == null ? other.getComment3() == null : this.getComment3().equals(other.getComment3()))
            && (this.getMark3date() == null ? other.getMark3date() == null : this.getMark3date().equals(other.getMark3date()))
            && (this.getValid() == null ? other.getValid() == null : this.getValid().equals(other.getValid()))
            && (this.getCdate() == null ? other.getCdate() == null : this.getCdate().equals(other.getCdate()))
            && (this.getMdate() == null ? other.getMdate() == null : this.getMdate().equals(other.getMdate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getThesisid() == null) ? 0 : getThesisid().hashCode());
        result = prime * result + ((getMark1() == null) ? 0 : getMark1().hashCode());
        result = prime * result + ((getComment1() == null) ? 0 : getComment1().hashCode());
        result = prime * result + ((getMark1date() == null) ? 0 : getMark1date().hashCode());
        result = prime * result + ((getMark2() == null) ? 0 : getMark2().hashCode());
        result = prime * result + ((getComment2() == null) ? 0 : getComment2().hashCode());
        result = prime * result + ((getMark2date() == null) ? 0 : getMark2date().hashCode());
        result = prime * result + ((getMark3() == null) ? 0 : getMark3().hashCode());
        result = prime * result + ((getComment3() == null) ? 0 : getComment3().hashCode());
        result = prime * result + ((getMark3date() == null) ? 0 : getMark3date().hashCode());
        result = prime * result + ((getValid() == null) ? 0 : getValid().hashCode());
        result = prime * result + ((getCdate() == null) ? 0 : getCdate().hashCode());
        result = prime * result + ((getMdate() == null) ? 0 : getMdate().hashCode());
        return result;
    }
}