package cn.zttek.thesis.modules.model;

@SuppressWarnings("serial")
public class Taskbook extends ThesisModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taskbook.task
     *
     * @mbggenerated
     */
    private String task;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taskbook.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taskbook.schedule
     *
     * @mbggenerated
     */
    private String schedule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taskbook.reference
     *
     * @mbggenerated
     */
    private String reference;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taskbook.tconfirm
     *
     * @mbggenerated
     */
    private Boolean tconfirm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taskbook.sconfirm
     *
     * @mbggenerated
     */
    private Boolean sconfirm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taskbook.task
     *
     * @return the value of taskbook.task
     *
     * @mbggenerated
     */
    public String getTask() {
        return task;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taskbook.task
     *
     * @param task the value for taskbook.task
     *
     * @mbggenerated
     */
    public void setTask(String task) {
        this.task = task == null ? null : task.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taskbook.content
     *
     * @return the value of taskbook.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taskbook.content
     *
     * @param content the value for taskbook.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taskbook.schedule
     *
     * @return the value of taskbook.schedule
     *
     * @mbggenerated
     */
    public String getSchedule() {
        return schedule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taskbook.schedule
     *
     * @param schedule the value for taskbook.schedule
     *
     * @mbggenerated
     */
    public void setSchedule(String schedule) {
        this.schedule = schedule == null ? null : schedule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taskbook.reference
     *
     * @return the value of taskbook.reference
     *
     * @mbggenerated
     */
    public String getReference() {
        return reference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taskbook.reference
     *
     * @param reference the value for taskbook.reference
     *
     * @mbggenerated
     */
    public void setReference(String reference) {
        this.reference = reference == null ? null : reference.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taskbook.tconfirm
     *
     * @return the value of taskbook.tconfirm
     *
     * @mbggenerated
     */
    public Boolean getTconfirm() {
        return tconfirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taskbook.tconfirm
     *
     * @param tconfirm the value for taskbook.tconfirm
     *
     * @mbggenerated
     */
    public void setTconfirm(Boolean tconfirm) {
        this.tconfirm = tconfirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taskbook.sconfirm
     *
     * @return the value of taskbook.sconfirm
     *
     * @mbggenerated
     */
    public Boolean getSconfirm() {
        return sconfirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taskbook.sconfirm
     *
     * @param sconfirm the value for taskbook.sconfirm
     *
     * @mbggenerated
     */
    public void setSconfirm(Boolean sconfirm) {
        this.sconfirm = sconfirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taskbook
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", task=").append(task);
        sb.append(", content=").append(content);
        sb.append(", schedule=").append(schedule);
        sb.append(", reference=").append(reference);
        sb.append(", tconfirm=").append(tconfirm);
        sb.append(", sconfirm=").append(sconfirm);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taskbook
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Taskbook other = (Taskbook) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getThesisid() == null ? other.getThesisid() == null : this.getThesisid().equals(other.getThesisid()))
            && (this.getTask() == null ? other.getTask() == null : this.getTask().equals(other.getTask()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getSchedule() == null ? other.getSchedule() == null : this.getSchedule().equals(other.getSchedule()))
            && (this.getReference() == null ? other.getReference() == null : this.getReference().equals(other.getReference()))
            && (this.getTconfirm() == null ? other.getTconfirm() == null : this.getTconfirm().equals(other.getTconfirm()))
            && (this.getSconfirm() == null ? other.getSconfirm() == null : this.getSconfirm().equals(other.getSconfirm()))
            && (this.getValid() == null ? other.getValid() == null : this.getValid().equals(other.getValid()))
            && (this.getCdate() == null ? other.getCdate() == null : this.getCdate().equals(other.getCdate()))
            && (this.getMdate() == null ? other.getMdate() == null : this.getMdate().equals(other.getMdate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taskbook
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getThesisid() == null) ? 0 : getThesisid().hashCode());
        result = prime * result + ((getTask() == null) ? 0 : getTask().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getSchedule() == null) ? 0 : getSchedule().hashCode());
        result = prime * result + ((getReference() == null) ? 0 : getReference().hashCode());
        result = prime * result + ((getTconfirm() == null) ? 0 : getTconfirm().hashCode());
        result = prime * result + ((getSconfirm() == null) ? 0 : getSconfirm().hashCode());
        result = prime * result + ((getValid() == null) ? 0 : getValid().hashCode());
        result = prime * result + ((getCdate() == null) ? 0 : getCdate().hashCode());
        result = prime * result + ((getMdate() == null) ? 0 : getMdate().hashCode());
        return result;
    }
}